# Generated by Django 3.1.5 on 2021-01-22 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20210119_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='characters.character')),
            ],
        ),
    ]
